name: Daily AI News Workflow

on:
  schedule:
    - cron: '18 21 * * *'  # This will run at 09:28 UTC (11:28 Paris time)
  workflow_dispatch:
    inputs:
      start_from:
        description: 'Start workflow from specific step'
        required: false
        type: choice
        options:
        - clear
        - fetch
        - download
        - parse
        - extract
        - summarise
      show_summaries:
        description: 'Show summaries after completion'
        required: false
        type: boolean
        default: false

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Create directories
      run: |
        mkdir -p logs
        mkdir -p database
        mkdir -p pdfs
        mkdir -p summaries
        mkdir -p results
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y poppler-utils  # For PDF processing

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install feedparser
        pip install pdfplumber
        pip install pytz
        # Add any other dependencies your script needs
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
    
    - name: Run workflow
      env:
        # Add any environment variables your script needs
        PYTHONPATH: ${{ github.workspace }}
      run: |
        if [ "${{ github.event.inputs.start_from }}" != "" ]; then
          python scripts/workflow.py --start-from ${{ github.event.inputs.start_from }}
        else
          python scripts/workflow.py
        fi
        
        if [ "${{ github.event.inputs.show_summaries }}" == "true" ]; then
          python scripts/workflow.py --show-summaries
        fi
    
    - name: Upload outputs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: workflow-outputs
        path: |
          workflow.log
          logs/*.log
          database/*.db
          summaries/*.json
          results/*.txt
          pdfs/*.pdf
